name = "fizzyhex/revy"
version = "0.5.4"
description = "Experimental bundle of ECS tooling"
authors = ["Fizzyhex"]
repository = "https://github.com/Fizzyhex/rbx-revy"
license = "MIT"
includes = [
  "pesde.toml",
  "README.md",
  "LICENSE",
  "dist/**/*.luau"
]

[target]
environment = "roblox"
build_files = ["dist"]
lib = "dist/init.luau"

[indices]
default = "https://github.com/pesde-pkg/index"

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[dev_dependencies]
scripts = { name = "pesde/scripts_rojo", version = "^0.2.0", target = "lune" }
rojo = { name = "pesde/rojo", version = "^7.5.1", target = "lune" }

[engines]
pesde = "^0.7.0"
lune = "^0.10.2"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[place]
shared = "game.ReplicatedStorage.Packages"

[dependencies]
jecs = { name = "marked/jecs", version = "^0.9.0" } # mirror of the wally package
replecs = { wally = "pepeeltoro41/replecs", version = "^0.0.2" }
planck = { wally = "yetanotherclown/planck", version = "^0.2.0" }
planck_jabby = { wally = "yetanotherclown/planck-jabby", version = "^0.2.0" }
planck_runservice = { wally = "yetanotherclown/planck-runservice", version = "^0.2.0" }
rewire = { wally = "sayhisam1/rewire", version = "^0.3.0" }
jabby = { name = "alicesaidhi/jabby", version = "^0.4.0-test.0" }

[overrides]
"replecs>jecs" = "jecs"
"jabby>jecs" = "jecs"
"planck>jecs" = "jecs"
"planck_jabby>jecs" = "jecs"
"planck_runservice>jecs" = "jecs"

"planck>jabby" = "jabby"
"planck_jabby>jabby" = "jabby"
"planck_runservice>jabby" = "jabby"
